version: '2'

services:
  # The application
  app:
    image: biigle/app-dev
    build:
      context: ./
      dockerfile: .docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"

  worker:
    image: biigle/worker-dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: .docker/worker.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"
    command: "php artisan queue:work --sleep=5 --tries=3 --timeout=0"

  # scheduler:
  #   image: biigle/worker-dev
  #   restart: unless-stopped
  #   build:
  #     context: ./
  #     dockerfile: .docker/worker.dockerfile
  #   working_dir: /var/www
  #   volumes_from:
  #     - app
  #   environment:
  #     - "DB_PORT=5432"
  #     - "DB_HOST=database"
  #   command: "while sleep 60; do php artisan schedule:run >> /dev/null 2>&1; done"

  # The web server
  web:
    image: biigle/web
    build:
      context: ./
      dockerfile: .docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8000:80

  # The database
  database:
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql
      - ./:/data
    environment:
      - "POSTGRES_DB=homestead"
      - "POSTGRES_USER=homestead"
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "54320:5432"

volumes:
  dbdata:

