version: '2'

services:

  app:
    image: biigle/app
    user: ${USER_ID}:${GROUP_ID}
    build:
      dockerfile: .docker/app.dockerfile
      context: ./
      args:
        GITHUB_OAUTH_TOKEN: ${GITHUB_OAUTH_TOKEN}
    env_file:
      - .env
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  web:
    image: biigle/web
    build:
      dockerfile: .docker/web.dockerfile
      context: ./

  worker:
    image: biigle/worker
    user: ${USER_ID}:${GROUP_ID}
    build:
      dockerfile: .docker/worker.dockerfile
      context: ./
    env_file:
      - .env
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
