name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    - name: Fetch worker image
      run: docker pull docker.pkg.github.com/biigle/core/worker:latest

    - name: Build the stack
      run: docker-compose up worker database_testing -d

    - name: Run tests
      run: composer run-script test
