name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Fetch base images
      run: |
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/worker:latest

    # - name: Build updated images
    #   run: |
    #     docker-compose build app worker

    - name: Build the stack
      run: docker-compose up -d --no-build worker database_testing
      env:
        USER_ID: 1000
        GROUP_ID: 1000

    - name: Run tests
      run: composer run-script test
