name: Tests

on: [push, pull_request]

jobs:
  test-current:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer
        restore-keys: |
          ${{ runner.os }}-composer

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Fetch base images
      run: |
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/app:latest
        docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/worker:latest

    - name: Start test database
      run: docker-compose up -d --no-build database_testing

    - name: Run tests
      run: docker-compose run --rm -u 1001 worker php -d memory_limit=1G vendor/bin/phpunit --random-order
